### ISSUE TITLE
UseStatusCodePagesWithReExecute shouldn't pass through the QueryString from the original request

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Diagnostics#267]
[This](https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNetCore.Diagnostics/StatusCodePage/StatusCodePagesExtensions.cs#L162) method currently will pass the Query string from the original request to the re-executed request, even though the path has changed. @Eilon  and I were thinking that it should probably be cleared and restored at the same time the original path is restored.

**Comment by ryanbrandenburg** [comment]
CC @Tratcher

**Comment by Eilon** [comment]
Indeed, using the original query string for the new request seems a tiny bit risky because it could quite likely affect the behavior of the sub-request. Obviously we don't want to clear *everything*, but if we change the path, we ought to change the rest of the URL, which means changing the query string.
