### ISSUE TITLE
Consider showing LoaderExceptions when caught exception is ReflectionTypeLoadException

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Diagnostics#315]
Based on discussion at https://github.com/aspnet/Mvc/issues/4892#issuecomment-227580313. It would be nice to type load exceptions so that it's easier to figure out what went wrong rather than see a generic message that tells you to read `LoaderExceptions`

**Comment by pranavkm** [comment]
cc @Eilon \  @rynowak \ @halter73 \ @davidfowl

**Comment by pranavkm** [comment]
Are there other exception types that would benefit from a similar treatment? `AggregateException`s for instance?

**Comment by pranavkm** [comment]
Also @ajaybhargavb who's assigned this work :)

**Comment by halter73** [comment]
If you wanted to be super generic you could think about some reflection based logging. Maybe JSON serialization. I haven't tried it out to see how it would look for ReflectionTypeLoadExceptions and AggregateExceptions, but it might be worth looking into.

**Comment by pranavkm** [comment]
Not sure I follow @halter73 - is this essentially serializing the exception to the log?

**Comment by halter73** [comment]
Since this issue is filed in the diagnostics repo, I thought it would be about how to display exceptions in the error pages, not how it's logged. But yes, I'm essentially suggesting serializing the exception if it can be done in a way that's not too verbose/distracting. Maybe it can be put in a collapsible section like the result of `Exception.ToString()` is today. 

I still think that MVC should catch `ReflectionTypeLoadExceptions` when it accesses `Assembly.DefinedTypes` and log it specially with `LoaderExceptions` like I suggest in https://github.com/aspnet/Mvc/issues/4892#issuecomment-227553247.

**Comment by Eilon** [comment]
@ajaybhargavb this is part of what we discussed earlier. Would be nice to special case some exception types and show more detailed information about them.
