### ISSUE TITLE
ExceptionHandlerMiddleware uses _next as default ExceptionHandler?!

### ISSUE THREAD

**Issue by NinoFloris** [aspnet/Diagnostics#400]
EDIT: The story is even weirder...

ExceptionHandlerMiddleware uses _next as default ExceptionHandler.
So let's say my aspnet controller throws an exception. this is bubbled and caught in the first try catch of the ExceptionHandlerMiddleware, then because most people will just run with the default `app.UseExceptionHandler()` we haven't explicitly set an ExceptionHandler and so it got set to `_next` by the constructor. This means we'll pointlessly run the same pipeline again in the second inner try catch: https://github.com/aspnet/Diagnostics/blob/4e044a1e30454b87edbc316f40ba608d1160cb28/src/Microsoft.AspNetCore.Diagnostics/ExceptionHandler/ExceptionHandlerMiddleware.cs#L74
this will of course result in the same exception 99% of the time.

And it also means most people will see two error log messages as for most of the cases (when `ExceptionHandler = _next`) will also log:
```cs
_logger.LogError(0, ex2, "An exception was thrown attempting to execute the error handler.");
```

Workaround:
```cs
var opts = new ExceptionHandlerOptions{ ExceptionHandler = ctx => Task.CompletedTask };
app.UseExceptionHandler(opts) 
```

This default is crazy, a waste of resources, and how this has never been reported is a mystery to me.

**Comment by Tratcher** [comment]
ExceptionHandler defaults to _next for the ExceptionHandlingPath scenario (though we should add a check in the constructor that ExceptionHandlingPath is actually set). This scenario is the one used in templates (`UseExceptionHandler("/error")`). I haven't seen the other scenarios used in the wild.

**Comment by davidfowl** [comment]
Why do we have that overload at all?

**Comment by Tratcher** [comment]
Which overload, the no params one? For DI.

**Comment by Eilon** [comment]
I believe this is what @Tratcher is talking about: There's a UseExceptionHandler overload that takes no params (aside from `this`): https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNetCore.Diagnostics/ExceptionHandler/ExceptionHandlerExtensions.cs#L19

And if you use it, the middleware will get its [options](https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNetCore.Diagnostics/ExceptionHandler/ExceptionHandlerOptions.cs) from DI in the [middlware ctor](https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNetCore.Diagnostics/ExceptionHandler/ExceptionHandlerMiddleware.cs#L26).

So, I think this is currently by design because it's just an incorrect usage of this middleware to not set options in DI (in service registration) **and** not pass in explicit options when using the middleware.

Having said that, we should consider having the ExceptionHandler middleware just throw its own unique error in the case that it is configured incorrectly, i.e. when an error happens and both `ExceptionHandlerOptions.ExceptionHandlingPath` and `ExceptionHandlerOptions.ExceptionHandler` are not set.

@Tratcher / others - thoughts on doing this new behavior?

**Comment by Tratcher** [comment]
Yes, that was my recommendation above. We can check this in the middleware constructor, we don't have to wait for an app error to occur.

**Comment by Eilon** [comment]
Ah sorry missed that in your post. We do need to check if *any* options are set, though, right? (Not just the path?)

**Comment by Tratcher** [comment]
The path and the ExceptionHandler are the only options.
