### ISSUE TITLE
RuntimeInfo page can display more information on KRE

### ISSUE THREAD

**Issue by suhasj** [aspnet/Diagnostics#41]
For runtime only the version is displayed. It would be good to display the architecture (x86/amd64), location from where it is picked up and clr type (coreclr/clr) as well

**Comment by Eilon** [comment]
@kichalla can you see if this is already all there?

**Comment by kichalla** [comment]
My bad, hadn't noticed @Eilon's comment...most of the content described in this bug is already present (but the issue also talks about `location` of DNX?...like is it interesting? also do we want to show `application base path` or `application version`?):

![image](https://cloud.githubusercontent.com/assets/6559784/9239466/d210346a-4110-11e5-9eff-025268663b14.png)

**Comment by Eilon** [comment]
I think what we have now is pretty good.

**Comment by kichalla** [comment]
ok, sure...then can I close the issue?

**Comment by Eilon** [comment]
Done :smile:
