### ISSUE TITLE
[Feature request] HealthCheckResult and health checks execution time

### ISSUE THREAD

**Issue by unaizorrilla** [aspnet/Diagnostics#491]
There is any plan to include the execution time ( or the whole execution time ) of health checks in the HealthCheckResult?

This data can be usefull for other stories like HealthCheck tracking results.
PR can be accepted?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @unaizorrilla.
@glennc, @rynowak thoughts? Including the `execution time` into the result seems like a reasonable ask to me. I would actually even think that the execution time would be useful per `HealthReportEntry`.

**Comment by rynowak** [comment]
Sure, we can this, this seems reasonable.

**Comment by unaizorrilla** [comment]
PR can be accepted?

**Comment by rynowak** [comment]
Sure

**Comment by rynowak** [comment]
Feel free to send a PR - if you don't get it together by lets say Weds next week then I will just do it so that it gets into preview3.

What I had in mind for this was to add `public TimeSpan Duration { get; }` property to `HealthReportEntry` and a `public TimeSpan TotalDuration { get; }` to `HealthReport`.

We already collect this data for logging, so this will be pretty easy:
https://github.com/aspnet/Diagnostics/blob/release/2.2/src/Microsoft.Extensions.Diagnostics.HealthChecks/DefaultHealthCheckService.cs#L49
https://github.com/aspnet/Diagnostics/blob/release/2.2/src/Microsoft.Extensions.Diagnostics.HealthChecks/DefaultHealthCheckService.cs#L83

**Comment by rynowak** [comment]
Thanks!
